services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belomax-nest-api
    working_dir: /usr/src/app
    volumes:
      - ./belomax-nest-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - redis
    command: yarn run start

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belomax-web
    working_dir: /usr/src/web
    volumes:
      - ./belomax-web:/usr/src/web
      - /usr/src/web/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - app
    command: yarn run dev

  db:
    image: postgres:13
    container_name: belomax-db
    environment:
      POSTGRES_USER: belomax
      POSTGRES_PASSWORD: belomaxpassword
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: belomax-redis
    ports:
      - "6379:6379"